import type { Muscle, Pattern } from "./muscles";
import type { EquipmentTier } from "./types";

/**
 * The exercise library is the single source of truth for exercise metadata.
 * `npm run seed:sql` regenerates supabase/seed_exercises.sql from this file,
 * so the database and the app can never drift apart.
 *
 * Tagging rules:
 *  - `primary` = muscles the exercise is a genuinely good stimulus for. Keep
 *    this short and honest; if everything claims everything, coverage
 *    analysis and substitutions both become useless.
 *  - `secondary` = meaningfully worked, but not why you'd pick the exercise.
 *  - `pattern` drives substitution: same pattern + same primaries means two
 *    exercises are near-interchangeable.
 */
export type LibraryExercise = {
  name: string;
  /** Coarse group, used for filtering and display. */
  group: string;
  equipment: EquipmentTier;
  pattern: Pattern;
  primary: Muscle[];
  secondary?: Muscle[];
  compound?: boolean;
  unilateral?: boolean;
};

export const EXERCISE_LIBRARY: LibraryExercise[] = [
  // ── Chest ──────────────────────────────────────────────────────────────
  { name: "Push-Up", group: "Chest", equipment: "bodyweight", pattern: "horizontal_push",
    primary: ["Mid Chest"], secondary: ["Front Delt", "Triceps Lateral Head", "Triceps Medial Head"], compound: true },
  { name: "Wide Push-Up", group: "Chest", equipment: "bodyweight", pattern: "horizontal_push",
    primary: ["Mid Chest"], secondary: ["Front Delt"], compound: true },
  { name: "Decline Push-Up (Feet Elevated)", group: "Chest", equipment: "bodyweight", pattern: "horizontal_push",
    primary: ["Upper Chest"], secondary: ["Front Delt", "Triceps Lateral Head"], compound: true },
  { name: "Incline Push-Up (Hands Elevated)", group: "Chest", equipment: "bodyweight", pattern: "horizontal_push",
    primary: ["Lower Chest", "Mid Chest"], secondary: ["Triceps Lateral Head"], compound: true },
  { name: "Deficit Push-Up", group: "Chest", equipment: "bodyweight", pattern: "horizontal_push",
    primary: ["Mid Chest"], secondary: ["Front Delt"], compound: true },
  { name: "Dumbbell Bench Press", group: "Chest", equipment: "home", pattern: "horizontal_push",
    primary: ["Mid Chest"], secondary: ["Front Delt", "Triceps Lateral Head"], compound: true },
  { name: "Dumbbell Incline Press", group: "Chest", equipment: "home", pattern: "horizontal_push",
    primary: ["Upper Chest"], secondary: ["Front Delt", "Triceps Lateral Head"], compound: true },
  { name: "Dumbbell Fly", group: "Chest", equipment: "home", pattern: "horizontal_push",
    primary: ["Mid Chest"], secondary: ["Front Delt"] },
  { name: "Dumbbell Incline Fly", group: "Chest", equipment: "home", pattern: "horizontal_push",
    primary: ["Upper Chest"], secondary: ["Front Delt"] },
  { name: "Resistance Band Chest Press", group: "Chest", equipment: "home", pattern: "horizontal_push",
    primary: ["Mid Chest"], secondary: ["Front Delt", "Triceps Lateral Head"], compound: true },
  { name: "Barbell Bench Press", group: "Chest", equipment: "full_gym", pattern: "horizontal_push",
    primary: ["Mid Chest"], secondary: ["Front Delt", "Triceps Lateral Head", "Triceps Medial Head"], compound: true },
  { name: "Incline Barbell Bench Press", group: "Chest", equipment: "full_gym", pattern: "horizontal_push",
    primary: ["Upper Chest"], secondary: ["Front Delt", "Triceps Lateral Head"], compound: true },
  { name: "Decline Barbell Bench Press", group: "Chest", equipment: "full_gym", pattern: "horizontal_push",
    primary: ["Lower Chest"], secondary: ["Triceps Lateral Head"], compound: true },
  { name: "Chest Press Machine", group: "Chest", equipment: "full_gym", pattern: "horizontal_push",
    primary: ["Mid Chest"], secondary: ["Front Delt", "Triceps Lateral Head"], compound: true },
  { name: "Incline Chest Press Machine", group: "Chest", equipment: "full_gym", pattern: "horizontal_push",
    primary: ["Upper Chest"], secondary: ["Front Delt"], compound: true },
  { name: "Smith Machine Bench Press", group: "Chest", equipment: "full_gym", pattern: "horizontal_push",
    primary: ["Mid Chest"], secondary: ["Front Delt", "Triceps Lateral Head"], compound: true },
  { name: "Cable Fly (Mid)", group: "Chest", equipment: "full_gym", pattern: "horizontal_push",
    primary: ["Mid Chest"], secondary: ["Front Delt"] },
  { name: "Low-to-High Cable Fly", group: "Chest", equipment: "full_gym", pattern: "horizontal_push",
    primary: ["Upper Chest"], secondary: ["Front Delt"] },
  { name: "High-to-Low Cable Crossover", group: "Chest", equipment: "full_gym", pattern: "horizontal_push",
    primary: ["Lower Chest"], secondary: ["Mid Chest"] },
  { name: "Pec Deck Machine", group: "Chest", equipment: "full_gym", pattern: "horizontal_push",
    primary: ["Mid Chest"], secondary: ["Front Delt"] },
  { name: "Chest Dip", group: "Chest", equipment: "full_gym", pattern: "horizontal_push",
    primary: ["Lower Chest"], secondary: ["Triceps Lateral Head", "Front Delt"], compound: true },

  // ── Back: vertical pull ────────────────────────────────────────────────
  { name: "Pull-Up", group: "Back", equipment: "home", pattern: "vertical_pull",
    primary: ["Lats", "Teres Major"], secondary: ["Lower Traps", "Biceps Long Head", "Brachialis"], compound: true },
  { name: "Chin-Up", group: "Back", equipment: "home", pattern: "vertical_pull",
    primary: ["Lats"], secondary: ["Biceps Short Head", "Biceps Long Head", "Lower Traps"], compound: true },
  { name: "Neutral-Grip Pull-Up", group: "Back", equipment: "home", pattern: "vertical_pull",
    primary: ["Lats"], secondary: ["Brachialis", "Biceps Long Head"], compound: true },
  { name: "Band-Assisted Pull-Up", group: "Back", equipment: "home", pattern: "vertical_pull",
    primary: ["Lats", "Teres Major"], secondary: ["Biceps Long Head"], compound: true },
  { name: "Lat Pulldown", group: "Back", equipment: "full_gym", pattern: "vertical_pull",
    primary: ["Lats", "Teres Major"], secondary: ["Lower Traps", "Biceps Long Head"], compound: true },
  { name: "Neutral-Grip Lat Pulldown", group: "Back", equipment: "full_gym", pattern: "vertical_pull",
    primary: ["Lats"], secondary: ["Brachialis", "Biceps Long Head"], compound: true },
  { name: "Assisted Pull-Up Machine", group: "Back", equipment: "full_gym", pattern: "vertical_pull",
    primary: ["Lats", "Teres Major"], secondary: ["Biceps Long Head"], compound: true },
  { name: "Straight-Arm Pulldown", group: "Back", equipment: "full_gym", pattern: "vertical_pull",
    primary: ["Lats"], secondary: ["Teres Major", "Triceps Long Head"] },

  // ── Back: horizontal pull ──────────────────────────────────────────────
  { name: "Inverted Row", group: "Back", equipment: "bodyweight", pattern: "horizontal_pull",
    primary: ["Lats", "Rhomboids", "Mid Traps"], secondary: ["Rear Delt", "Biceps Long Head"], compound: true },
  { name: "Underhand Inverted Row", group: "Back", equipment: "bodyweight", pattern: "horizontal_pull",
    primary: ["Lats", "Biceps Long Head", "Biceps Short Head"], secondary: ["Rhomboids", "Brachialis"], compound: true },
  { name: "Towel Row (Door Anchor)", group: "Back", equipment: "bodyweight", pattern: "horizontal_pull",
    primary: ["Lats", "Rhomboids"], secondary: ["Biceps Long Head", "Forearm Flexors"], compound: true },
  { name: "Prone Y-T-W Raise", group: "Back", equipment: "bodyweight", pattern: "shoulder_horizontal_abduction",
    primary: ["Rear Delt", "Lower Traps"], secondary: ["Rhomboids", "Rotator Cuff"] },
  { name: "Superman", group: "Back", equipment: "bodyweight", pattern: "hinge",
    primary: ["Spinal Erectors"], secondary: ["Glute Max"] },
  { name: "Dumbbell Row", group: "Back", equipment: "home", pattern: "horizontal_pull",
    primary: ["Lats", "Rhomboids"], secondary: ["Mid Traps", "Rear Delt", "Biceps Long Head"], compound: true, unilateral: true },
  { name: "Dumbbell Renegade Row", group: "Back", equipment: "home", pattern: "horizontal_pull",
    primary: ["Lats", "Rhomboids"], secondary: ["Deep Core", "Obliques"], compound: true, unilateral: true },
  { name: "Chest-Supported Dumbbell Row", group: "Back", equipment: "home", pattern: "horizontal_pull",
    primary: ["Rhomboids", "Mid Traps"], secondary: ["Lats", "Rear Delt"], compound: true },
  { name: "Doorway Resistance Band Row", group: "Back", equipment: "home", pattern: "horizontal_pull",
    primary: ["Rhomboids", "Mid Traps"], secondary: ["Lats", "Biceps Long Head"], compound: true },
  { name: "Resistance Band Pull-Apart", group: "Back", equipment: "home", pattern: "shoulder_horizontal_abduction",
    primary: ["Rear Delt", "Rhomboids"], secondary: ["Mid Traps"] },
  { name: "Barbell Row", group: "Back", equipment: "full_gym", pattern: "horizontal_pull",
    primary: ["Lats", "Rhomboids", "Mid Traps"], secondary: ["Rear Delt", "Spinal Erectors", "Biceps Long Head"], compound: true },
  { name: "Pendlay Row", group: "Back", equipment: "full_gym", pattern: "horizontal_pull",
    primary: ["Rhomboids", "Mid Traps", "Lats"], secondary: ["Spinal Erectors", "Rear Delt"], compound: true },
  { name: "T-Bar Row", group: "Back", equipment: "full_gym", pattern: "horizontal_pull",
    primary: ["Lats", "Rhomboids", "Mid Traps"], secondary: ["Rear Delt", "Biceps Long Head"], compound: true },
  { name: "Seated Cable Row", group: "Back", equipment: "full_gym", pattern: "horizontal_pull",
    primary: ["Rhomboids", "Mid Traps", "Lats"], secondary: ["Rear Delt", "Biceps Long Head"], compound: true },
  { name: "Single-Arm Cable Row", group: "Back", equipment: "full_gym", pattern: "horizontal_pull",
    primary: ["Lats", "Rhomboids"], secondary: ["Rear Delt"], compound: true, unilateral: true },
  { name: "Chest-Supported Machine Row", group: "Back", equipment: "full_gym", pattern: "horizontal_pull",
    primary: ["Rhomboids", "Mid Traps"], secondary: ["Lats", "Rear Delt"], compound: true },

  // ── Back / posterior chain: hinge ──────────────────────────────────────
  { name: "Deadlift", group: "Back", equipment: "full_gym", pattern: "hinge",
    primary: ["Spinal Erectors", "Glute Max", "Hamstrings (Hip)"], secondary: ["Lats", "Upper Traps", "Quads (Vastii)"], compound: true },
  { name: "Sumo Deadlift", group: "Back", equipment: "full_gym", pattern: "hinge",
    primary: ["Glute Max", "Quads (Vastii)", "Adductors"], secondary: ["Spinal Erectors", "Hamstrings (Hip)"], compound: true },
  { name: "Trap Bar Deadlift", group: "Back", equipment: "full_gym", pattern: "hinge",
    primary: ["Glute Max", "Quads (Vastii)"], secondary: ["Spinal Erectors", "Hamstrings (Hip)", "Upper Traps"], compound: true },
  { name: "Rack Pull", group: "Back", equipment: "full_gym", pattern: "hinge",
    primary: ["Spinal Erectors", "Upper Traps"], secondary: ["Glute Max", "Lats"], compound: true },
  { name: "Back Extension", group: "Back", equipment: "full_gym", pattern: "hinge",
    primary: ["Spinal Erectors", "Hamstrings (Hip)"], secondary: ["Glute Max"] },
  { name: "45-Degree Hyperextension", group: "Back", equipment: "full_gym", pattern: "hinge",
    primary: ["Hamstrings (Hip)", "Glute Max"], secondary: ["Spinal Erectors"] },

  // ── Traps ──────────────────────────────────────────────────────────────
  { name: "Dumbbell Shrug", group: "Traps", equipment: "home", pattern: "shrug",
    primary: ["Upper Traps"], secondary: ["Forearm Flexors"] },
  { name: "Farmer's Carry", group: "Traps", equipment: "home", pattern: "carry",
    primary: ["Upper Traps", "Forearm Flexors"], secondary: ["Deep Core", "Obliques"] },
  { name: "Barbell Shrug", group: "Traps", equipment: "full_gym", pattern: "shrug",
    primary: ["Upper Traps"], secondary: ["Forearm Flexors"] },
  { name: "Cable Shrug", group: "Traps", equipment: "full_gym", pattern: "shrug",
    primary: ["Upper Traps"] },

  // ── Shoulders: vertical push (front delt) ──────────────────────────────
  { name: "Pike Push-Up", group: "Shoulders", equipment: "bodyweight", pattern: "vertical_push",
    primary: ["Front Delt"], secondary: ["Triceps Lateral Head", "Upper Chest"], compound: true },
  { name: "Handstand Push-Up", group: "Shoulders", equipment: "bodyweight", pattern: "vertical_push",
    primary: ["Front Delt"], secondary: ["Triceps Lateral Head", "Upper Traps"], compound: true },
  { name: "Wall Handstand Hold", group: "Shoulders", equipment: "bodyweight", pattern: "vertical_push",
    primary: ["Front Delt"], secondary: ["Side Delt", "Upper Traps", "Deep Core"] },
  { name: "Elevated Pike Push-Up", group: "Shoulders", equipment: "bodyweight", pattern: "vertical_push",
    primary: ["Front Delt"], secondary: ["Side Delt", "Triceps Lateral Head"], compound: true },
  { name: "Dumbbell Shoulder Press", group: "Shoulders", equipment: "home", pattern: "vertical_push",
    primary: ["Front Delt"], secondary: ["Side Delt", "Triceps Lateral Head", "Upper Traps"], compound: true },
  { name: "Arnold Press", group: "Shoulders", equipment: "home", pattern: "vertical_push",
    primary: ["Front Delt", "Side Delt"], secondary: ["Triceps Lateral Head"], compound: true },
  { name: "Seated Dumbbell Press", group: "Shoulders", equipment: "home", pattern: "vertical_push",
    primary: ["Front Delt"], secondary: ["Side Delt", "Triceps Lateral Head"], compound: true },
  { name: "Barbell Overhead Press", group: "Shoulders", equipment: "full_gym", pattern: "vertical_push",
    primary: ["Front Delt"], secondary: ["Side Delt", "Triceps Lateral Head", "Upper Traps"], compound: true },
  { name: "Push Press", group: "Shoulders", equipment: "full_gym", pattern: "vertical_push",
    primary: ["Front Delt"], secondary: ["Triceps Lateral Head", "Quads (Vastii)"], compound: true },
  { name: "Shoulder Press Machine", group: "Shoulders", equipment: "full_gym", pattern: "vertical_push",
    primary: ["Front Delt"], secondary: ["Side Delt", "Triceps Lateral Head"], compound: true },
  { name: "Landmine Press", group: "Shoulders", equipment: "full_gym", pattern: "vertical_push",
    primary: ["Front Delt", "Upper Chest"], secondary: ["Triceps Lateral Head"], compound: true, unilateral: true },

  // ── Shoulders: side delt (abduction) ───────────────────────────────────
  { name: "Lateral Raise", group: "Shoulders", equipment: "home", pattern: "shoulder_abduction",
    primary: ["Side Delt"], secondary: ["Front Delt"] },
  { name: "Leaning Lateral Raise", group: "Shoulders", equipment: "home", pattern: "shoulder_abduction",
    primary: ["Side Delt"], unilateral: true },
  { name: "Resistance Band Lateral Raise", group: "Shoulders", equipment: "home", pattern: "shoulder_abduction",
    primary: ["Side Delt"] },
  { name: "Cable Lateral Raise", group: "Shoulders", equipment: "full_gym", pattern: "shoulder_abduction",
    primary: ["Side Delt"], unilateral: true },
  { name: "Machine Lateral Raise", group: "Shoulders", equipment: "full_gym", pattern: "shoulder_abduction",
    primary: ["Side Delt"] },
  { name: "Upright Row", group: "Shoulders", equipment: "full_gym", pattern: "shoulder_abduction",
    primary: ["Side Delt", "Upper Traps"], secondary: ["Biceps Long Head"], compound: true },

  // ── Shoulders: rear delt (horizontal abduction) ────────────────────────
  { name: "Bent-Over Reverse Fly", group: "Shoulders", equipment: "home", pattern: "shoulder_horizontal_abduction",
    primary: ["Rear Delt"], secondary: ["Rhomboids", "Mid Traps"] },
  { name: "Face Pull", group: "Shoulders", equipment: "full_gym", pattern: "shoulder_horizontal_abduction",
    primary: ["Rear Delt", "Rotator Cuff"], secondary: ["Mid Traps", "Rhomboids"] },
  { name: "Reverse Pec Deck", group: "Shoulders", equipment: "full_gym", pattern: "shoulder_horizontal_abduction",
    primary: ["Rear Delt"], secondary: ["Rhomboids", "Mid Traps"] },
  { name: "Cable Rear Delt Fly", group: "Shoulders", equipment: "full_gym", pattern: "shoulder_horizontal_abduction",
    primary: ["Rear Delt"], secondary: ["Mid Traps"], unilateral: true },
  { name: "Front Raise", group: "Shoulders", equipment: "home", pattern: "vertical_push",
    primary: ["Front Delt"] },
  { name: "External Rotation (Band)", group: "Shoulders", equipment: "home", pattern: "shoulder_horizontal_abduction",
    primary: ["Rotator Cuff"], secondary: ["Rear Delt"] },

  // ── Biceps ─────────────────────────────────────────────────────────────
  { name: "Dumbbell Bicep Curl", group: "Biceps", equipment: "home", pattern: "elbow_flexion",
    primary: ["Biceps Long Head", "Biceps Short Head"], secondary: ["Brachialis"] },
  { name: "Incline Dumbbell Curl", group: "Biceps", equipment: "home", pattern: "elbow_flexion",
    primary: ["Biceps Long Head"], secondary: ["Brachialis"] },
  { name: "Hammer Curl", group: "Biceps", equipment: "home", pattern: "elbow_flexion",
    primary: ["Brachialis", "Brachioradialis"], secondary: ["Biceps Long Head"] },
  { name: "Concentration Curl", group: "Biceps", equipment: "home", pattern: "elbow_flexion",
    primary: ["Biceps Short Head"], secondary: ["Brachialis"], unilateral: true },
  { name: "Resistance Band Curl", group: "Biceps", equipment: "home", pattern: "elbow_flexion",
    primary: ["Biceps Long Head", "Biceps Short Head"] },
  { name: "Barbell Curl", group: "Biceps", equipment: "full_gym", pattern: "elbow_flexion",
    primary: ["Biceps Long Head", "Biceps Short Head"], secondary: ["Brachialis"] },
  { name: "EZ-Bar Curl", group: "Biceps", equipment: "full_gym", pattern: "elbow_flexion",
    primary: ["Biceps Long Head", "Biceps Short Head"], secondary: ["Brachioradialis"] },
  { name: "Preacher Curl", group: "Biceps", equipment: "full_gym", pattern: "elbow_flexion",
    primary: ["Biceps Short Head"], secondary: ["Brachialis"] },
  { name: "Spider Curl", group: "Biceps", equipment: "full_gym", pattern: "elbow_flexion",
    primary: ["Biceps Short Head"], secondary: ["Brachialis"] },
  { name: "Cable Curl", group: "Biceps", equipment: "full_gym", pattern: "elbow_flexion",
    primary: ["Biceps Long Head", "Biceps Short Head"] },
  { name: "Bayesian Cable Curl", group: "Biceps", equipment: "full_gym", pattern: "elbow_flexion",
    primary: ["Biceps Long Head"], secondary: ["Brachialis"], unilateral: true },

  // ── Triceps ────────────────────────────────────────────────────────────
  { name: "Tricep Dip (Bench)", group: "Triceps", equipment: "bodyweight", pattern: "elbow_extension",
    primary: ["Triceps Lateral Head", "Triceps Medial Head"], secondary: ["Front Delt", "Lower Chest"], compound: true },
  { name: "Diamond Push-Up", group: "Triceps", equipment: "bodyweight", pattern: "elbow_extension",
    primary: ["Triceps Lateral Head", "Triceps Medial Head"], secondary: ["Mid Chest"], compound: true },
  { name: "Close-Grip Push-Up", group: "Triceps", equipment: "bodyweight", pattern: "elbow_extension",
    primary: ["Triceps Lateral Head", "Triceps Medial Head"], secondary: ["Mid Chest"], compound: true },
  { name: "Bodyweight Skull Crusher", group: "Triceps", equipment: "bodyweight", pattern: "elbow_extension",
    primary: ["Triceps Long Head"], secondary: ["Triceps Lateral Head"] },
  { name: "Overhead Dumbbell Tricep Extension", group: "Triceps", equipment: "home", pattern: "elbow_extension",
    primary: ["Triceps Long Head"], secondary: ["Triceps Medial Head"] },
  { name: "Single-Arm Overhead Extension", group: "Triceps", equipment: "home", pattern: "elbow_extension",
    primary: ["Triceps Long Head"], unilateral: true },
  { name: "Tricep Kickback", group: "Triceps", equipment: "home", pattern: "elbow_extension",
    primary: ["Triceps Lateral Head"], secondary: ["Triceps Long Head"], unilateral: true },
  { name: "Resistance Band Pushdown", group: "Triceps", equipment: "home", pattern: "elbow_extension",
    primary: ["Triceps Lateral Head"], secondary: ["Triceps Medial Head"] },
  { name: "Close-Grip Bench Press", group: "Triceps", equipment: "full_gym", pattern: "elbow_extension",
    primary: ["Triceps Lateral Head", "Triceps Medial Head"], secondary: ["Mid Chest", "Front Delt"], compound: true },
  { name: "Cable Tricep Pushdown", group: "Triceps", equipment: "full_gym", pattern: "elbow_extension",
    primary: ["Triceps Lateral Head"], secondary: ["Triceps Medial Head"] },
  { name: "Rope Pushdown", group: "Triceps", equipment: "full_gym", pattern: "elbow_extension",
    primary: ["Triceps Lateral Head"], secondary: ["Triceps Medial Head"] },
  { name: "Overhead Cable Extension", group: "Triceps", equipment: "full_gym", pattern: "elbow_extension",
    primary: ["Triceps Long Head"], secondary: ["Triceps Medial Head"] },
  { name: "Skull Crusher", group: "Triceps", equipment: "full_gym", pattern: "elbow_extension",
    primary: ["Triceps Long Head"], secondary: ["Triceps Lateral Head"] },
  { name: "JM Press", group: "Triceps", equipment: "full_gym", pattern: "elbow_extension",
    primary: ["Triceps Long Head", "Triceps Medial Head"], compound: true },
  { name: "Tricep Dip Machine", group: "Triceps", equipment: "full_gym", pattern: "elbow_extension",
    primary: ["Triceps Lateral Head", "Triceps Medial Head"] },

  // ── Forearms ───────────────────────────────────────────────────────────
  { name: "Dead Hang", group: "Forearms", equipment: "home", pattern: "carry",
    primary: ["Forearm Flexors"], secondary: ["Lats"] },
  { name: "Wrist Curl (Dumbbell)", group: "Forearms", equipment: "home", pattern: "elbow_flexion",
    primary: ["Forearm Flexors"] },
  { name: "Reverse Wrist Curl (Dumbbell)", group: "Forearms", equipment: "home", pattern: "elbow_flexion",
    primary: ["Brachioradialis"] },
  { name: "Plate Pinch Hold", group: "Forearms", equipment: "home", pattern: "carry",
    primary: ["Forearm Flexors"] },
  { name: "Barbell Reverse Curl", group: "Forearms", equipment: "full_gym", pattern: "elbow_flexion",
    primary: ["Brachioradialis", "Brachialis"] },
  { name: "Cable Wrist Curl", group: "Forearms", equipment: "full_gym", pattern: "elbow_flexion",
    primary: ["Forearm Flexors"] },

  // ── Quads: squat pattern ───────────────────────────────────────────────
  { name: "Bodyweight Squat", group: "Quads", equipment: "bodyweight", pattern: "squat",
    primary: ["Quads (Vastii)"], secondary: ["Glute Max", "Adductors"], compound: true },
  { name: "Jump Squat", group: "Quads", equipment: "bodyweight", pattern: "squat",
    primary: ["Quads (Vastii)"], secondary: ["Glute Max", "Gastrocnemius"], compound: true },
  { name: "Wall Sit", group: "Quads", equipment: "bodyweight", pattern: "squat",
    primary: ["Quads (Vastii)"] },
  { name: "Goblet Squat", group: "Quads", equipment: "home", pattern: "squat",
    primary: ["Quads (Vastii)"], secondary: ["Glute Max", "Deep Core"], compound: true },
  { name: "Resistance Band Squat", group: "Quads", equipment: "home", pattern: "squat",
    primary: ["Quads (Vastii)"], secondary: ["Glute Max"], compound: true },
  { name: "Barbell Back Squat", group: "Quads", equipment: "full_gym", pattern: "squat",
    primary: ["Quads (Vastii)", "Glute Max"], secondary: ["Adductors", "Spinal Erectors"], compound: true },
  { name: "Barbell Front Squat", group: "Quads", equipment: "full_gym", pattern: "squat",
    primary: ["Quads (Vastii)"], secondary: ["Glute Max", "Spinal Erectors", "Deep Core"], compound: true },
  { name: "Hack Squat", group: "Quads", equipment: "full_gym", pattern: "squat",
    primary: ["Quads (Vastii)"], secondary: ["Glute Max"], compound: true },
  { name: "Leg Press", group: "Quads", equipment: "full_gym", pattern: "squat",
    primary: ["Quads (Vastii)"], secondary: ["Glute Max", "Adductors"], compound: true },
  { name: "Smith Machine Squat", group: "Quads", equipment: "full_gym", pattern: "squat",
    primary: ["Quads (Vastii)"], secondary: ["Glute Max"], compound: true },
  { name: "Pendulum Squat", group: "Quads", equipment: "full_gym", pattern: "squat",
    primary: ["Quads (Vastii)"], secondary: ["Glute Max"], compound: true },

  // ── Quads: knee extension (the only way to load rectus femoris short) ──
  { name: "Leg Extension", group: "Quads", equipment: "full_gym", pattern: "knee_extension",
    primary: ["Rectus Femoris", "Quads (Vastii)"] },
  { name: "Sissy Squat", group: "Quads", equipment: "bodyweight", pattern: "knee_extension",
    primary: ["Rectus Femoris", "Quads (Vastii)"] },
  { name: "Reverse Nordic Curl", group: "Quads", equipment: "bodyweight", pattern: "knee_extension",
    primary: ["Rectus Femoris", "Quads (Vastii)"] },

  // ── Quads / glutes: lunge pattern ──────────────────────────────────────
  { name: "Lunge", group: "Quads", equipment: "bodyweight", pattern: "lunge",
    primary: ["Quads (Vastii)", "Glute Max"], secondary: ["Adductors", "Glute Medius"], compound: true, unilateral: true },
  { name: "Walking Lunge", group: "Quads", equipment: "bodyweight", pattern: "lunge",
    primary: ["Quads (Vastii)", "Glute Max"], secondary: ["Adductors"], compound: true, unilateral: true },
  { name: "Reverse Lunge", group: "Quads", equipment: "bodyweight", pattern: "lunge",
    primary: ["Glute Max", "Quads (Vastii)"], secondary: ["Hamstrings (Hip)"], compound: true, unilateral: true },
  { name: "Bulgarian Split Squat", group: "Quads", equipment: "bodyweight", pattern: "lunge",
    primary: ["Quads (Vastii)", "Glute Max"], secondary: ["Glute Medius", "Adductors"], compound: true, unilateral: true },
  { name: "Step-Up", group: "Quads", equipment: "bodyweight", pattern: "lunge",
    primary: ["Quads (Vastii)", "Glute Max"], secondary: ["Glute Medius"], compound: true, unilateral: true },
  { name: "Dumbbell Lunge", group: "Quads", equipment: "home", pattern: "lunge",
    primary: ["Quads (Vastii)", "Glute Max"], secondary: ["Adductors"], compound: true, unilateral: true },
  { name: "Dumbbell Step-Up", group: "Quads", equipment: "home", pattern: "lunge",
    primary: ["Quads (Vastii)", "Glute Max"], secondary: ["Glute Medius"], compound: true, unilateral: true },
  { name: "Walking Lunge (Barbell)", group: "Quads", equipment: "full_gym", pattern: "lunge",
    primary: ["Quads (Vastii)", "Glute Max"], secondary: ["Adductors"], compound: true, unilateral: true },

  // ── Hamstrings: hip-dominant (long head BF + semimembranosus) ──────────
  { name: "Single-Leg Deadlift (Bodyweight)", group: "Hamstrings", equipment: "bodyweight", pattern: "hinge",
    primary: ["Hamstrings (Hip)", "Glute Max"], secondary: ["Glute Medius", "Spinal Erectors"], compound: true, unilateral: true },
  { name: "Dumbbell Romanian Deadlift", group: "Hamstrings", equipment: "home", pattern: "hinge",
    primary: ["Hamstrings (Hip)", "Glute Max"], secondary: ["Spinal Erectors"], compound: true },
  { name: "Dumbbell Stiff-Leg Deadlift", group: "Hamstrings", equipment: "home", pattern: "hinge",
    primary: ["Hamstrings (Hip)"], secondary: ["Glute Max", "Spinal Erectors"], compound: true },
  { name: "Single-Leg Dumbbell RDL", group: "Hamstrings", equipment: "home", pattern: "hinge",
    primary: ["Hamstrings (Hip)", "Glute Max"], secondary: ["Glute Medius"], compound: true, unilateral: true },
  { name: "Barbell Romanian Deadlift", group: "Hamstrings", equipment: "full_gym", pattern: "hinge",
    primary: ["Hamstrings (Hip)", "Glute Max"], secondary: ["Spinal Erectors"], compound: true },
  { name: "Good Morning", group: "Hamstrings", equipment: "full_gym", pattern: "hinge",
    primary: ["Hamstrings (Hip)"], secondary: ["Glute Max", "Spinal Erectors"], compound: true },
  { name: "Cable Pull-Through", group: "Hamstrings", equipment: "full_gym", pattern: "hinge",
    primary: ["Glute Max", "Hamstrings (Hip)"], compound: true },

  // ── Hamstrings: knee-dominant (short head BF + semitendinosus) ─────────
  // Needs only anchored feet (a couch or a partner), so genuinely bodyweight.
  { name: "Nordic Curl", group: "Hamstrings", equipment: "bodyweight", pattern: "knee_flexion",
    primary: ["Hamstrings (Knee)"], secondary: ["Glute Max"] },
  { name: "Sliding Leg Curl (Towel)", group: "Hamstrings", equipment: "bodyweight", pattern: "knee_flexion",
    primary: ["Hamstrings (Knee)"], secondary: ["Glute Max"] },
  { name: "Swiss Ball Leg Curl", group: "Hamstrings", equipment: "home", pattern: "knee_flexion",
    primary: ["Hamstrings (Knee)"], secondary: ["Glute Max"] },
  { name: "Lying Leg Curl", group: "Hamstrings", equipment: "full_gym", pattern: "knee_flexion",
    primary: ["Hamstrings (Knee)"] },
  { name: "Seated Leg Curl", group: "Hamstrings", equipment: "full_gym", pattern: "knee_flexion",
    primary: ["Hamstrings (Knee)", "Hamstrings (Hip)"] },
  { name: "Glute-Ham Raise", group: "Hamstrings", equipment: "full_gym", pattern: "knee_flexion",
    primary: ["Hamstrings (Knee)"], secondary: ["Glute Max", "Spinal Erectors"] },

  // ── Glutes ─────────────────────────────────────────────────────────────
  { name: "Glute Bridge", group: "Glutes", equipment: "bodyweight", pattern: "hip_thrust",
    primary: ["Glute Max"], secondary: ["Hamstrings (Hip)"] },
  { name: "Single-Leg Glute Bridge", group: "Glutes", equipment: "bodyweight", pattern: "hip_thrust",
    primary: ["Glute Max"], secondary: ["Hamstrings (Hip)", "Glute Medius"], unilateral: true },
  { name: "Donkey Kick", group: "Glutes", equipment: "bodyweight", pattern: "hip_thrust",
    primary: ["Glute Max"], unilateral: true },
  { name: "Fire Hydrant", group: "Glutes", equipment: "bodyweight", pattern: "hip_abduction",
    primary: ["Glute Medius"], secondary: ["Glute Max"], unilateral: true },
  { name: "Clamshell", group: "Glutes", equipment: "bodyweight", pattern: "hip_abduction",
    primary: ["Glute Medius"], unilateral: true },
  { name: "Band Lateral Walk", group: "Glutes", equipment: "home", pattern: "hip_abduction",
    primary: ["Glute Medius"], secondary: ["Glute Max"] },
  { name: "Dumbbell Hip Thrust", group: "Glutes", equipment: "home", pattern: "hip_thrust",
    primary: ["Glute Max"], secondary: ["Hamstrings (Hip)"] },
  { name: "Resistance Band Hip Thrust", group: "Glutes", equipment: "home", pattern: "hip_thrust",
    primary: ["Glute Max"], secondary: ["Hamstrings (Hip)"] },
  { name: "Barbell Hip Thrust", group: "Glutes", equipment: "full_gym", pattern: "hip_thrust",
    primary: ["Glute Max"], secondary: ["Hamstrings (Hip)"] },
  { name: "Machine Hip Thrust", group: "Glutes", equipment: "full_gym", pattern: "hip_thrust",
    primary: ["Glute Max"], secondary: ["Hamstrings (Hip)"] },
  { name: "Cable Glute Kickback", group: "Glutes", equipment: "full_gym", pattern: "hip_thrust",
    primary: ["Glute Max"], unilateral: true },
  { name: "Hip Abduction Machine", group: "Glutes", equipment: "full_gym", pattern: "hip_abduction",
    primary: ["Glute Medius"], secondary: ["Glute Max"] },

  // ── Calves (knee straight = gastroc, knee bent = soleus) ───────────────
  { name: "Standing Calf Raise", group: "Calves", equipment: "bodyweight", pattern: "calf_raise",
    primary: ["Gastrocnemius"], secondary: ["Soleus"] },
  { name: "Single-Leg Calf Raise", group: "Calves", equipment: "bodyweight", pattern: "calf_raise",
    primary: ["Gastrocnemius"], secondary: ["Soleus"], unilateral: true },
  { name: "Dumbbell Calf Raise", group: "Calves", equipment: "home", pattern: "calf_raise",
    primary: ["Gastrocnemius"], secondary: ["Soleus"] },
  // Knee bent takes the gastrocnemius out, isolating the soleus — no load needed.
  { name: "Seated Bodyweight Calf Raise", group: "Calves", equipment: "bodyweight", pattern: "calf_raise",
    primary: ["Soleus"] },
  { name: "Bent-Knee Wall Calf Raise", group: "Calves", equipment: "bodyweight", pattern: "calf_raise",
    primary: ["Soleus"] },
  { name: "Standing Calf Raise Machine", group: "Calves", equipment: "full_gym", pattern: "calf_raise",
    primary: ["Gastrocnemius"], secondary: ["Soleus"] },
  { name: "Seated Calf Raise Machine", group: "Calves", equipment: "full_gym", pattern: "calf_raise",
    primary: ["Soleus"] },
  { name: "Leg Press Calf Raise", group: "Calves", equipment: "full_gym", pattern: "calf_raise",
    primary: ["Gastrocnemius"], secondary: ["Soleus"] },

  // ── Core ───────────────────────────────────────────────────────────────
  { name: "Plank", group: "Core", equipment: "bodyweight", pattern: "core_anti_extension",
    primary: ["Deep Core"], secondary: ["Rectus Abdominis"] },
  { name: "Side Plank", group: "Core", equipment: "bodyweight", pattern: "core_rotation",
    primary: ["Obliques"], secondary: ["Deep Core"], unilateral: true },
  { name: "Dead Bug", group: "Core", equipment: "bodyweight", pattern: "core_anti_extension",
    primary: ["Deep Core"], secondary: ["Rectus Abdominis"] },
  { name: "Hollow Body Hold", group: "Core", equipment: "bodyweight", pattern: "core_anti_extension",
    primary: ["Rectus Abdominis"], secondary: ["Deep Core"] },
  { name: "Sit-Up", group: "Core", equipment: "bodyweight", pattern: "core_flexion",
    primary: ["Rectus Abdominis"], secondary: ["Obliques"] },
  { name: "Crunch", group: "Core", equipment: "bodyweight", pattern: "core_flexion",
    primary: ["Rectus Abdominis"] },
  { name: "Bicycle Crunch", group: "Core", equipment: "bodyweight", pattern: "core_rotation",
    primary: ["Obliques", "Rectus Abdominis"] },
  { name: "Leg Raise", group: "Core", equipment: "bodyweight", pattern: "core_flexion",
    primary: ["Rectus Abdominis"], secondary: ["Deep Core"] },
  { name: "Flutter Kick", group: "Core", equipment: "bodyweight", pattern: "core_flexion",
    primary: ["Rectus Abdominis"] },
  { name: "V-Up", group: "Core", equipment: "bodyweight", pattern: "core_flexion",
    primary: ["Rectus Abdominis"], secondary: ["Obliques"] },
  { name: "Mountain Climber", group: "Core", equipment: "bodyweight", pattern: "core_anti_extension",
    primary: ["Deep Core"], secondary: ["Rectus Abdominis"] },
  { name: "Russian Twist", group: "Core", equipment: "bodyweight", pattern: "core_rotation",
    primary: ["Obliques"] },
  { name: "Weighted Russian Twist", group: "Core", equipment: "home", pattern: "core_rotation",
    primary: ["Obliques"] },
  { name: "Weighted Sit-Up", group: "Core", equipment: "home", pattern: "core_flexion",
    primary: ["Rectus Abdominis"], secondary: ["Obliques"] },
  { name: "Ab Wheel Rollout", group: "Core", equipment: "home", pattern: "core_anti_extension",
    primary: ["Deep Core", "Rectus Abdominis"] },
  { name: "Cable Crunch", group: "Core", equipment: "full_gym", pattern: "core_flexion",
    primary: ["Rectus Abdominis"], secondary: ["Obliques"] },
  { name: "Hanging Leg Raise", group: "Core", equipment: "full_gym", pattern: "core_flexion",
    primary: ["Rectus Abdominis"], secondary: ["Deep Core", "Forearm Flexors"] },
  { name: "Captain's Chair Leg Raise", group: "Core", equipment: "full_gym", pattern: "core_flexion",
    primary: ["Rectus Abdominis"], secondary: ["Deep Core"] },
  { name: "Landmine Twist", group: "Core", equipment: "full_gym", pattern: "core_rotation",
    primary: ["Obliques"], secondary: ["Deep Core"] },
  { name: "Pallof Press", group: "Core", equipment: "full_gym", pattern: "core_rotation",
    primary: ["Obliques", "Deep Core"] },

  // ── Full body / conditioning ───────────────────────────────────────────
  { name: "Burpee", group: "Full Body", equipment: "bodyweight", pattern: "conditioning",
    primary: ["Quads (Vastii)", "Mid Chest"], secondary: ["Front Delt", "Deep Core"], compound: true },
  { name: "Jumping Jack", group: "Full Body", equipment: "bodyweight", pattern: "conditioning",
    primary: ["Gastrocnemius"], secondary: ["Side Delt"] },
  { name: "High Knees", group: "Full Body", equipment: "bodyweight", pattern: "conditioning",
    primary: ["Rectus Femoris"], secondary: ["Gastrocnemius"] },
  { name: "Bear Crawl", group: "Full Body", equipment: "bodyweight", pattern: "conditioning",
    primary: ["Deep Core"], secondary: ["Front Delt", "Quads (Vastii)"] },
  { name: "Jump Rope", group: "Full Body", equipment: "home", pattern: "conditioning",
    primary: ["Gastrocnemius"], secondary: ["Soleus"] },
  { name: "Kettlebell Swing", group: "Full Body", equipment: "home", pattern: "hinge",
    primary: ["Glute Max", "Hamstrings (Hip)"], secondary: ["Spinal Erectors", "Deep Core"], compound: true },
  { name: "Dumbbell Thruster", group: "Full Body", equipment: "home", pattern: "conditioning",
    primary: ["Quads (Vastii)", "Front Delt"], secondary: ["Glute Max", "Triceps Lateral Head"], compound: true },
  { name: "Man Maker", group: "Full Body", equipment: "home", pattern: "conditioning",
    primary: ["Quads (Vastii)", "Lats"], secondary: ["Front Delt", "Deep Core"], compound: true },
  { name: "Barbell Clean and Press", group: "Full Body", equipment: "full_gym", pattern: "conditioning",
    primary: ["Front Delt", "Quads (Vastii)"], secondary: ["Upper Traps", "Glute Max"], compound: true },
  { name: "Barbell Clean", group: "Full Body", equipment: "full_gym", pattern: "conditioning",
    primary: ["Glute Max", "Upper Traps"], secondary: ["Quads (Vastii)", "Hamstrings (Hip)"], compound: true },
  { name: "Barbell Snatch", group: "Full Body", equipment: "full_gym", pattern: "conditioning",
    primary: ["Glute Max", "Upper Traps", "Front Delt"], secondary: ["Quads (Vastii)"], compound: true },
  { name: "Rowing Machine", group: "Full Body", equipment: "full_gym", pattern: "conditioning",
    primary: ["Lats", "Quads (Vastii)"], secondary: ["Rhomboids", "Biceps Long Head"], compound: true },
  { name: "Battle Ropes", group: "Full Body", equipment: "full_gym", pattern: "conditioning",
    primary: ["Front Delt"], secondary: ["Deep Core", "Side Delt"] },
  { name: "Assault Bike", group: "Full Body", equipment: "full_gym", pattern: "conditioning",
    primary: ["Quads (Vastii)"], secondary: ["Front Delt", "Lats"] },
  { name: "Sled Push", group: "Full Body", equipment: "full_gym", pattern: "conditioning",
    primary: ["Quads (Vastii)", "Glute Max"], secondary: ["Gastrocnemius"], compound: true },
  { name: "Box Jump", group: "Full Body", equipment: "full_gym", pattern: "conditioning",
    primary: ["Quads (Vastii)", "Glute Max"], secondary: ["Gastrocnemius"], compound: true },
];

/** Fast lookup by name — names are unique across the library. */
export const LIBRARY_BY_NAME = new Map(
  EXERCISE_LIBRARY.map((e) => [e.name, e]),
);
