-- GENERATED FILE — do not edit by hand.
-- Source: src/lib/exercise-library.ts   Regenerate: npm run seed:sql
--
-- Run this in the Supabase SQL Editor after 003_exercise_science.sql.
-- Idempotent: inserts new exercises, refreshes tagging on existing ones.
--
-- Equipment tiers are cumulative minimums: a 'bodyweight' exercise is
-- available to every user, 'home' to home + full_gym users, 'full_gym' only
-- at a full gym. Filter with a rank comparison, never an exact match.

insert into public.exercises
  (name, muscle_group, equipment, movement_pattern,
   primary_muscles, secondary_muscles, is_compound, is_unilateral)
values
  ('Push-Up', 'Chest', 'bodyweight', 'horizontal_push', ARRAY['Mid Chest'], ARRAY['Front Delt', 'Triceps Lateral Head', 'Triceps Medial Head'], true, false),
  ('Dumbbell Bench Press', 'Chest', 'home', 'horizontal_push', ARRAY['Mid Chest'], ARRAY['Front Delt', 'Triceps Lateral Head'], true, false),
  ('Dumbbell Incline Press', 'Chest', 'home', 'horizontal_push', ARRAY['Upper Chest'], ARRAY['Front Delt', 'Triceps Lateral Head'], true, false),
  ('Dumbbell Fly', 'Chest', 'home', 'horizontal_push', ARRAY['Mid Chest'], ARRAY['Front Delt'], false, false),
  ('Dumbbell Incline Fly', 'Chest', 'home', 'horizontal_push', ARRAY['Upper Chest'], ARRAY['Front Delt'], false, false),
  ('Barbell Bench Press', 'Chest', 'full_gym', 'horizontal_push', ARRAY['Mid Chest'], ARRAY['Front Delt', 'Triceps Lateral Head', 'Triceps Medial Head'], true, false),
  ('Incline Barbell Bench Press', 'Chest', 'full_gym', 'horizontal_push', ARRAY['Upper Chest'], ARRAY['Front Delt', 'Triceps Lateral Head'], true, false),
  ('Decline Barbell Bench Press', 'Chest', 'full_gym', 'horizontal_push', ARRAY['Lower Chest'], ARRAY['Triceps Lateral Head'], true, false),
  ('Chest Press Machine', 'Chest', 'full_gym', 'horizontal_push', ARRAY['Mid Chest'], ARRAY['Front Delt', 'Triceps Lateral Head'], true, false),
  ('Incline Chest Press Machine', 'Chest', 'full_gym', 'horizontal_push', ARRAY['Upper Chest'], ARRAY['Front Delt'], true, false),
  ('Smith Machine Bench Press', 'Chest', 'full_gym', 'horizontal_push', ARRAY['Mid Chest'], ARRAY['Front Delt', 'Triceps Lateral Head'], true, false),
  ('Cable Fly (Mid)', 'Chest', 'full_gym', 'horizontal_push', ARRAY['Mid Chest'], ARRAY['Front Delt'], false, false),
  ('Low-to-High Cable Fly', 'Chest', 'full_gym', 'horizontal_push', ARRAY['Upper Chest'], ARRAY['Front Delt'], false, false),
  ('High-to-Low Cable Crossover', 'Chest', 'full_gym', 'horizontal_push', ARRAY['Lower Chest'], ARRAY['Mid Chest'], false, false),
  ('Pec Deck Machine', 'Chest', 'full_gym', 'horizontal_push', ARRAY['Mid Chest'], ARRAY['Front Delt'], false, false),
  ('Chest Dip', 'Chest', 'full_gym', 'horizontal_push', ARRAY['Lower Chest'], ARRAY['Triceps Lateral Head', 'Front Delt'], true, false),
  ('Pull-Up', 'Back', 'home', 'vertical_pull', ARRAY['Lats', 'Teres Major'], ARRAY['Lower Traps', 'Biceps Long Head', 'Brachialis'], true, false),
  ('Chin-Up', 'Back', 'home', 'vertical_pull', ARRAY['Lats'], ARRAY['Biceps Short Head', 'Biceps Long Head', 'Lower Traps'], true, false),
  ('Neutral-Grip Pull-Up', 'Back', 'home', 'vertical_pull', ARRAY['Lats'], ARRAY['Brachialis', 'Biceps Long Head'], true, false),
  ('Band-Assisted Pull-Up', 'Back', 'home', 'vertical_pull', ARRAY['Lats', 'Teres Major'], ARRAY['Biceps Long Head'], true, false),
  ('Lat Pulldown', 'Back', 'full_gym', 'vertical_pull', ARRAY['Lats', 'Teres Major'], ARRAY['Lower Traps', 'Biceps Long Head'], true, false),
  ('Neutral-Grip Lat Pulldown', 'Back', 'full_gym', 'vertical_pull', ARRAY['Lats'], ARRAY['Brachialis', 'Biceps Long Head'], true, false),
  ('Assisted Pull-Up Machine', 'Back', 'full_gym', 'vertical_pull', ARRAY['Lats', 'Teres Major'], ARRAY['Biceps Long Head'], true, false),
  ('Straight-Arm Pulldown', 'Back', 'full_gym', 'vertical_pull', ARRAY['Lats'], ARRAY['Teres Major', 'Triceps Long Head'], false, false),
  ('Inverted Row', 'Back', 'bodyweight', 'horizontal_pull', ARRAY['Lats', 'Rhomboids', 'Mid Traps'], ARRAY['Rear Delt', 'Biceps Long Head'], true, false),
  ('Underhand Inverted Row', 'Back', 'bodyweight', 'horizontal_pull', ARRAY['Lats', 'Biceps Long Head', 'Biceps Short Head'], ARRAY['Rhomboids', 'Brachialis'], true, false),
  ('Dumbbell Row', 'Back', 'home', 'horizontal_pull', ARRAY['Lats', 'Rhomboids'], ARRAY['Mid Traps', 'Rear Delt', 'Biceps Long Head'], true, true),
  ('Chest-Supported Dumbbell Row', 'Back', 'home', 'horizontal_pull', ARRAY['Rhomboids', 'Mid Traps'], ARRAY['Lats', 'Rear Delt'], true, false),
  ('Resistance Band Pull-Apart', 'Back', 'home', 'shoulder_horizontal_abduction', ARRAY['Rear Delt', 'Rhomboids'], ARRAY['Mid Traps'], false, false),
  ('Barbell Row', 'Back', 'full_gym', 'horizontal_pull', ARRAY['Lats', 'Rhomboids', 'Mid Traps'], ARRAY['Rear Delt', 'Spinal Erectors', 'Biceps Long Head'], true, false),
  ('T-Bar Row', 'Back', 'full_gym', 'horizontal_pull', ARRAY['Lats', 'Rhomboids', 'Mid Traps'], ARRAY['Rear Delt', 'Biceps Long Head'], true, false),
  ('Seated Cable Row', 'Back', 'full_gym', 'horizontal_pull', ARRAY['Rhomboids', 'Mid Traps', 'Lats'], ARRAY['Rear Delt', 'Biceps Long Head'], true, false),
  ('Single-Arm Cable Row', 'Back', 'full_gym', 'horizontal_pull', ARRAY['Lats', 'Rhomboids'], ARRAY['Rear Delt'], true, true),
  ('Chest-Supported Machine Row', 'Back', 'full_gym', 'horizontal_pull', ARRAY['Rhomboids', 'Mid Traps'], ARRAY['Lats', 'Rear Delt'], true, false),
  ('Deadlift', 'Back', 'full_gym', 'hinge', ARRAY['Spinal Erectors', 'Glute Max', 'Hamstrings (Hip)'], ARRAY['Lats', 'Upper Traps', 'Quads (Vastii)'], true, false),
  ('Trap Bar Deadlift', 'Back', 'full_gym', 'hinge', ARRAY['Glute Max', 'Quads (Vastii)'], ARRAY['Spinal Erectors', 'Hamstrings (Hip)', 'Upper Traps'], true, false),
  ('Rack Pull', 'Back', 'full_gym', 'hinge', ARRAY['Spinal Erectors', 'Upper Traps'], ARRAY['Glute Max', 'Lats'], true, false),
  ('Back Extension', 'Back', 'full_gym', 'hinge', ARRAY['Spinal Erectors', 'Hamstrings (Hip)'], ARRAY['Glute Max'], false, false),
  ('45-Degree Hyperextension', 'Back', 'full_gym', 'hinge', ARRAY['Hamstrings (Hip)', 'Glute Max'], ARRAY['Spinal Erectors'], false, false),
  ('Dumbbell Shrug', 'Traps', 'home', 'shrug', ARRAY['Upper Traps'], ARRAY['Forearm Flexors'], false, false),
  ('Farmer''s Carry', 'Traps', 'home', 'carry', ARRAY['Upper Traps', 'Forearm Flexors'], ARRAY['Deep Core', 'Obliques'], false, false),
  ('Barbell Shrug', 'Traps', 'full_gym', 'shrug', ARRAY['Upper Traps'], ARRAY['Forearm Flexors'], false, false),
  ('Pike Push-Up', 'Shoulders', 'bodyweight', 'vertical_push', ARRAY['Front Delt'], ARRAY['Triceps Lateral Head', 'Upper Chest'], true, false),
  ('Elevated Pike Push-Up', 'Shoulders', 'bodyweight', 'vertical_push', ARRAY['Front Delt'], ARRAY['Side Delt', 'Triceps Lateral Head'], true, false),
  ('Dumbbell Shoulder Press', 'Shoulders', 'home', 'vertical_push', ARRAY['Front Delt'], ARRAY['Side Delt', 'Triceps Lateral Head', 'Upper Traps'], true, false),
  ('Seated Dumbbell Press', 'Shoulders', 'home', 'vertical_push', ARRAY['Front Delt'], ARRAY['Side Delt', 'Triceps Lateral Head'], true, false),
  ('Barbell Overhead Press', 'Shoulders', 'full_gym', 'vertical_push', ARRAY['Front Delt'], ARRAY['Side Delt', 'Triceps Lateral Head', 'Upper Traps'], true, false),
  ('Push Press', 'Shoulders', 'full_gym', 'vertical_push', ARRAY['Front Delt'], ARRAY['Triceps Lateral Head', 'Quads (Vastii)'], true, false),
  ('Shoulder Press Machine', 'Shoulders', 'full_gym', 'vertical_push', ARRAY['Front Delt'], ARRAY['Side Delt', 'Triceps Lateral Head'], true, false),
  ('Landmine Press', 'Shoulders', 'full_gym', 'vertical_push', ARRAY['Front Delt', 'Upper Chest'], ARRAY['Triceps Lateral Head'], true, true),
  ('Lateral Raise', 'Shoulders', 'home', 'shoulder_abduction', ARRAY['Side Delt'], ARRAY['Front Delt'], false, false),
  ('Resistance Band Lateral Raise', 'Shoulders', 'home', 'shoulder_abduction', ARRAY['Side Delt'], '{}', false, false),
  ('Cable Lateral Raise', 'Shoulders', 'full_gym', 'shoulder_abduction', ARRAY['Side Delt'], '{}', false, true),
  ('Machine Lateral Raise', 'Shoulders', 'full_gym', 'shoulder_abduction', ARRAY['Side Delt'], '{}', false, false),
  ('Bent-Over Reverse Fly', 'Shoulders', 'home', 'shoulder_horizontal_abduction', ARRAY['Rear Delt'], ARRAY['Rhomboids', 'Mid Traps'], false, false),
  ('Face Pull', 'Shoulders', 'full_gym', 'shoulder_horizontal_abduction', ARRAY['Rear Delt', 'Rotator Cuff'], ARRAY['Mid Traps', 'Rhomboids'], false, false),
  ('Reverse Pec Deck', 'Shoulders', 'full_gym', 'shoulder_horizontal_abduction', ARRAY['Rear Delt'], ARRAY['Rhomboids', 'Mid Traps'], false, false),
  ('Cable Rear Delt Fly', 'Shoulders', 'full_gym', 'shoulder_horizontal_abduction', ARRAY['Rear Delt'], ARRAY['Mid Traps'], false, true),
  ('Front Raise', 'Shoulders', 'home', 'vertical_push', ARRAY['Front Delt'], '{}', false, false),
  ('External Rotation (Band)', 'Shoulders', 'home', 'shoulder_horizontal_abduction', ARRAY['Rotator Cuff'], ARRAY['Rear Delt'], false, false),
  ('Dumbbell Bicep Curl', 'Biceps', 'home', 'elbow_flexion', ARRAY['Biceps Long Head', 'Biceps Short Head'], ARRAY['Brachialis'], false, false),
  ('Incline Dumbbell Curl', 'Biceps', 'home', 'elbow_flexion', ARRAY['Biceps Long Head'], ARRAY['Brachialis'], false, false),
  ('Hammer Curl', 'Biceps', 'home', 'elbow_flexion', ARRAY['Brachialis', 'Brachioradialis'], ARRAY['Biceps Long Head'], false, false),
  ('Resistance Band Curl', 'Biceps', 'home', 'elbow_flexion', ARRAY['Biceps Long Head', 'Biceps Short Head'], '{}', false, false),
  ('Barbell Curl', 'Biceps', 'full_gym', 'elbow_flexion', ARRAY['Biceps Long Head', 'Biceps Short Head'], ARRAY['Brachialis'], false, false),
  ('EZ-Bar Curl', 'Biceps', 'full_gym', 'elbow_flexion', ARRAY['Biceps Long Head', 'Biceps Short Head'], ARRAY['Brachioradialis'], false, false),
  ('Preacher Curl', 'Biceps', 'full_gym', 'elbow_flexion', ARRAY['Biceps Short Head'], ARRAY['Brachialis'], false, false),
  ('Spider Curl', 'Biceps', 'full_gym', 'elbow_flexion', ARRAY['Biceps Short Head'], ARRAY['Brachialis'], false, false),
  ('Cable Curl', 'Biceps', 'full_gym', 'elbow_flexion', ARRAY['Biceps Long Head', 'Biceps Short Head'], '{}', false, false),
  ('Bayesian Cable Curl', 'Biceps', 'full_gym', 'elbow_flexion', ARRAY['Biceps Long Head'], ARRAY['Brachialis'], false, true),
  ('Tricep Dip (Bench)', 'Triceps', 'bodyweight', 'elbow_extension', ARRAY['Triceps Lateral Head', 'Triceps Medial Head'], ARRAY['Front Delt', 'Lower Chest'], true, false),
  ('Diamond Push-Up', 'Triceps', 'bodyweight', 'elbow_extension', ARRAY['Triceps Lateral Head', 'Triceps Medial Head'], ARRAY['Mid Chest'], true, false),
  ('Close-Grip Push-Up', 'Triceps', 'bodyweight', 'elbow_extension', ARRAY['Triceps Lateral Head', 'Triceps Medial Head'], ARRAY['Mid Chest'], true, false),
  ('Bodyweight Skull Crusher', 'Triceps', 'bodyweight', 'elbow_extension', ARRAY['Triceps Long Head'], ARRAY['Triceps Lateral Head'], false, false),
  ('Overhead Dumbbell Tricep Extension', 'Triceps', 'home', 'elbow_extension', ARRAY['Triceps Long Head'], ARRAY['Triceps Medial Head'], false, false),
  ('Single-Arm Overhead Extension', 'Triceps', 'home', 'elbow_extension', ARRAY['Triceps Long Head'], '{}', false, true),
  ('Tricep Kickback', 'Triceps', 'home', 'elbow_extension', ARRAY['Triceps Lateral Head'], ARRAY['Triceps Long Head'], false, true),
  ('Resistance Band Pushdown', 'Triceps', 'home', 'elbow_extension', ARRAY['Triceps Lateral Head'], ARRAY['Triceps Medial Head'], false, false),
  ('Close-Grip Bench Press', 'Triceps', 'full_gym', 'elbow_extension', ARRAY['Triceps Lateral Head', 'Triceps Medial Head'], ARRAY['Mid Chest', 'Front Delt'], true, false),
  ('Cable Tricep Pushdown', 'Triceps', 'full_gym', 'elbow_extension', ARRAY['Triceps Lateral Head'], ARRAY['Triceps Medial Head'], false, false),
  ('Rope Pushdown', 'Triceps', 'full_gym', 'elbow_extension', ARRAY['Triceps Lateral Head'], ARRAY['Triceps Medial Head'], false, false),
  ('Overhead Cable Extension', 'Triceps', 'full_gym', 'elbow_extension', ARRAY['Triceps Long Head'], ARRAY['Triceps Medial Head'], false, false),
  ('Skull Crusher', 'Triceps', 'full_gym', 'elbow_extension', ARRAY['Triceps Long Head'], ARRAY['Triceps Lateral Head'], false, false),
  ('JM Press', 'Triceps', 'full_gym', 'elbow_extension', ARRAY['Triceps Long Head', 'Triceps Medial Head'], '{}', true, false),
  ('Tricep Dip Machine', 'Triceps', 'full_gym', 'elbow_extension', ARRAY['Triceps Lateral Head', 'Triceps Medial Head'], '{}', false, false),
  ('Dead Hang', 'Forearms', 'home', 'carry', ARRAY['Forearm Flexors'], ARRAY['Lats'], false, false),
  ('Wrist Curl (Dumbbell)', 'Forearms', 'home', 'elbow_flexion', ARRAY['Forearm Flexors'], '{}', false, false),
  ('Reverse Wrist Curl (Dumbbell)', 'Forearms', 'home', 'elbow_flexion', ARRAY['Brachioradialis'], '{}', false, false),
  ('Plate Pinch Hold', 'Forearms', 'home', 'carry', ARRAY['Forearm Flexors'], '{}', false, false),
  ('Barbell Reverse Curl', 'Forearms', 'full_gym', 'elbow_flexion', ARRAY['Brachioradialis', 'Brachialis'], '{}', false, false),
  ('Cable Wrist Curl', 'Forearms', 'full_gym', 'elbow_flexion', ARRAY['Forearm Flexors'], '{}', false, false),
  ('Bodyweight Squat', 'Quads', 'bodyweight', 'squat', ARRAY['Quads (Vastii)'], ARRAY['Glute Max', 'Adductors'], true, false),
  ('Jump Squat', 'Quads', 'bodyweight', 'squat', ARRAY['Quads (Vastii)'], ARRAY['Glute Max', 'Gastrocnemius'], true, false),
  ('Wall Sit', 'Quads', 'bodyweight', 'squat', ARRAY['Quads (Vastii)'], '{}', false, false),
  ('Goblet Squat', 'Quads', 'home', 'squat', ARRAY['Quads (Vastii)'], ARRAY['Glute Max', 'Deep Core'], true, false),
  ('Resistance Band Squat', 'Quads', 'home', 'squat', ARRAY['Quads (Vastii)'], ARRAY['Glute Max'], true, false),
  ('Barbell Back Squat', 'Quads', 'full_gym', 'squat', ARRAY['Quads (Vastii)', 'Glute Max'], ARRAY['Adductors', 'Spinal Erectors'], true, false),
  ('Barbell Front Squat', 'Quads', 'full_gym', 'squat', ARRAY['Quads (Vastii)'], ARRAY['Glute Max', 'Spinal Erectors', 'Deep Core'], true, false),
  ('Hack Squat', 'Quads', 'full_gym', 'squat', ARRAY['Quads (Vastii)'], ARRAY['Glute Max'], true, false),
  ('Leg Press', 'Quads', 'full_gym', 'squat', ARRAY['Quads (Vastii)'], ARRAY['Glute Max', 'Adductors'], true, false),
  ('Smith Machine Squat', 'Quads', 'full_gym', 'squat', ARRAY['Quads (Vastii)'], ARRAY['Glute Max'], true, false),
  ('Pendulum Squat', 'Quads', 'full_gym', 'squat', ARRAY['Quads (Vastii)'], ARRAY['Glute Max'], true, false),
  ('Leg Extension', 'Quads', 'full_gym', 'knee_extension', ARRAY['Rectus Femoris', 'Quads (Vastii)'], '{}', false, false),
  ('Sissy Squat', 'Quads', 'bodyweight', 'knee_extension', ARRAY['Rectus Femoris', 'Quads (Vastii)'], '{}', false, false),
  ('Reverse Nordic Curl', 'Quads', 'bodyweight', 'knee_extension', ARRAY['Rectus Femoris', 'Quads (Vastii)'], '{}', false, false),
  ('Lunge', 'Quads', 'bodyweight', 'lunge', ARRAY['Quads (Vastii)', 'Glute Max'], ARRAY['Adductors', 'Glute Medius'], true, true),
  ('Walking Lunge', 'Quads', 'bodyweight', 'lunge', ARRAY['Quads (Vastii)', 'Glute Max'], ARRAY['Adductors'], true, true),
  ('Reverse Lunge', 'Quads', 'bodyweight', 'lunge', ARRAY['Glute Max', 'Quads (Vastii)'], ARRAY['Hamstrings (Hip)'], true, true),
  ('Bulgarian Split Squat', 'Quads', 'bodyweight', 'lunge', ARRAY['Quads (Vastii)', 'Glute Max'], ARRAY['Glute Medius', 'Adductors'], true, true),
  ('Step-Up', 'Quads', 'bodyweight', 'lunge', ARRAY['Quads (Vastii)', 'Glute Max'], ARRAY['Glute Medius'], true, true),
  ('Dumbbell Lunge', 'Quads', 'home', 'lunge', ARRAY['Quads (Vastii)', 'Glute Max'], ARRAY['Adductors'], true, true),
  ('Dumbbell Step-Up', 'Quads', 'home', 'lunge', ARRAY['Quads (Vastii)', 'Glute Max'], ARRAY['Glute Medius'], true, true),
  ('Single-Leg Deadlift (Bodyweight)', 'Hamstrings', 'bodyweight', 'hinge', ARRAY['Hamstrings (Hip)', 'Glute Max'], ARRAY['Glute Medius', 'Spinal Erectors'], true, true),
  ('Dumbbell Romanian Deadlift', 'Hamstrings', 'home', 'hinge', ARRAY['Hamstrings (Hip)', 'Glute Max'], ARRAY['Spinal Erectors'], true, false),
  ('Dumbbell Stiff-Leg Deadlift', 'Hamstrings', 'home', 'hinge', ARRAY['Hamstrings (Hip)'], ARRAY['Glute Max', 'Spinal Erectors'], true, false),
  ('Single-Leg Dumbbell RDL', 'Hamstrings', 'home', 'hinge', ARRAY['Hamstrings (Hip)', 'Glute Max'], ARRAY['Glute Medius'], true, true),
  ('Barbell Romanian Deadlift', 'Hamstrings', 'full_gym', 'hinge', ARRAY['Hamstrings (Hip)', 'Glute Max'], ARRAY['Spinal Erectors'], true, false),
  ('Good Morning', 'Hamstrings', 'full_gym', 'hinge', ARRAY['Hamstrings (Hip)'], ARRAY['Glute Max', 'Spinal Erectors'], true, false),
  ('Nordic Curl', 'Hamstrings', 'bodyweight', 'knee_flexion', ARRAY['Hamstrings (Knee)'], ARRAY['Glute Max'], false, false),
  ('Swiss Ball Leg Curl', 'Hamstrings', 'home', 'knee_flexion', ARRAY['Hamstrings (Knee)'], ARRAY['Glute Max'], false, false),
  ('Lying Leg Curl', 'Hamstrings', 'full_gym', 'knee_flexion', ARRAY['Hamstrings (Knee)'], '{}', false, false),
  ('Seated Leg Curl', 'Hamstrings', 'full_gym', 'knee_flexion', ARRAY['Hamstrings (Knee)', 'Hamstrings (Hip)'], '{}', false, false),
  ('Glute Bridge', 'Glutes', 'bodyweight', 'hip_thrust', ARRAY['Glute Max'], ARRAY['Hamstrings (Hip)'], false, false),
  ('Band Lateral Walk', 'Glutes', 'home', 'hip_abduction', ARRAY['Glute Medius'], ARRAY['Glute Max'], false, false),
  ('Dumbbell Hip Thrust', 'Glutes', 'home', 'hip_thrust', ARRAY['Glute Max'], ARRAY['Hamstrings (Hip)'], false, false),
  ('Resistance Band Hip Thrust', 'Glutes', 'home', 'hip_thrust', ARRAY['Glute Max'], ARRAY['Hamstrings (Hip)'], false, false),
  ('Barbell Hip Thrust', 'Glutes', 'full_gym', 'hip_thrust', ARRAY['Glute Max'], ARRAY['Hamstrings (Hip)'], false, false),
  ('Machine Hip Thrust', 'Glutes', 'full_gym', 'hip_thrust', ARRAY['Glute Max'], ARRAY['Hamstrings (Hip)'], false, false),
  ('Cable Glute Kickback', 'Glutes', 'full_gym', 'hip_thrust', ARRAY['Glute Max'], '{}', false, true),
  ('Hip Abduction Machine', 'Glutes', 'full_gym', 'hip_abduction', ARRAY['Glute Medius'], ARRAY['Glute Max'], false, false),
  ('Standing Calf Raise', 'Calves', 'bodyweight', 'calf_raise', ARRAY['Gastrocnemius'], ARRAY['Soleus'], false, false),
  ('Single-Leg Calf Raise', 'Calves', 'bodyweight', 'calf_raise', ARRAY['Gastrocnemius'], ARRAY['Soleus'], false, true),
  ('Dumbbell Calf Raise', 'Calves', 'home', 'calf_raise', ARRAY['Gastrocnemius'], ARRAY['Soleus'], false, false),
  ('Seated Bodyweight Calf Raise', 'Calves', 'bodyweight', 'calf_raise', ARRAY['Soleus'], '{}', false, false),
  ('Bent-Knee Wall Calf Raise', 'Calves', 'bodyweight', 'calf_raise', ARRAY['Soleus'], '{}', false, false),
  ('Standing Calf Raise Machine', 'Calves', 'full_gym', 'calf_raise', ARRAY['Gastrocnemius'], ARRAY['Soleus'], false, false),
  ('Seated Calf Raise Machine', 'Calves', 'full_gym', 'calf_raise', ARRAY['Soleus'], '{}', false, false),
  ('Leg Press Calf Raise', 'Calves', 'full_gym', 'calf_raise', ARRAY['Gastrocnemius'], ARRAY['Soleus'], false, false),
  ('Plank', 'Core', 'bodyweight', 'core_anti_extension', ARRAY['Deep Core'], ARRAY['Rectus Abdominis'], false, false),
  ('Side Plank', 'Core', 'bodyweight', 'core_rotation', ARRAY['Obliques'], ARRAY['Deep Core'], false, true),
  ('Dead Bug', 'Core', 'bodyweight', 'core_anti_extension', ARRAY['Deep Core'], ARRAY['Rectus Abdominis'], false, false),
  ('Hollow Body Hold', 'Core', 'bodyweight', 'core_anti_extension', ARRAY['Rectus Abdominis'], ARRAY['Deep Core'], false, false),
  ('Sit-Up', 'Core', 'bodyweight', 'core_flexion', ARRAY['Rectus Abdominis'], ARRAY['Obliques'], false, false),
  ('Crunch', 'Core', 'bodyweight', 'core_flexion', ARRAY['Rectus Abdominis'], '{}', false, false),
  ('Bicycle Crunch', 'Core', 'bodyweight', 'core_rotation', ARRAY['Obliques', 'Rectus Abdominis'], '{}', false, false),
  ('Leg Raise', 'Core', 'bodyweight', 'core_flexion', ARRAY['Rectus Abdominis'], ARRAY['Deep Core'], false, false),
  ('Flutter Kick', 'Core', 'bodyweight', 'core_flexion', ARRAY['Rectus Abdominis'], '{}', false, false),
  ('V-Up', 'Core', 'bodyweight', 'core_flexion', ARRAY['Rectus Abdominis'], ARRAY['Obliques'], false, false),
  ('Mountain Climber', 'Core', 'bodyweight', 'core_anti_extension', ARRAY['Deep Core'], ARRAY['Rectus Abdominis'], false, false),
  ('Russian Twist', 'Core', 'bodyweight', 'core_rotation', ARRAY['Obliques'], '{}', false, false),
  ('Weighted Russian Twist', 'Core', 'home', 'core_rotation', ARRAY['Obliques'], '{}', false, false),
  ('Weighted Sit-Up', 'Core', 'home', 'core_flexion', ARRAY['Rectus Abdominis'], ARRAY['Obliques'], false, false),
  ('Ab Wheel Rollout', 'Core', 'home', 'core_anti_extension', ARRAY['Deep Core', 'Rectus Abdominis'], '{}', false, false),
  ('Cable Crunch', 'Core', 'full_gym', 'core_flexion', ARRAY['Rectus Abdominis'], ARRAY['Obliques'], false, false),
  ('Hanging Leg Raise', 'Core', 'full_gym', 'core_flexion', ARRAY['Rectus Abdominis'], ARRAY['Deep Core', 'Forearm Flexors'], false, false),
  ('Captain''s Chair Leg Raise', 'Core', 'full_gym', 'core_flexion', ARRAY['Rectus Abdominis'], ARRAY['Deep Core'], false, false),
  ('Landmine Twist', 'Core', 'full_gym', 'core_rotation', ARRAY['Obliques'], ARRAY['Deep Core'], false, false),
  ('Pallof Press', 'Core', 'full_gym', 'core_rotation', ARRAY['Obliques', 'Deep Core'], '{}', false, false),
  ('Burpee', 'Full Body', 'bodyweight', 'conditioning', ARRAY['Quads (Vastii)', 'Mid Chest'], ARRAY['Front Delt', 'Deep Core'], true, false),
  ('Jumping Jack', 'Full Body', 'bodyweight', 'conditioning', ARRAY['Gastrocnemius'], ARRAY['Side Delt'], false, false),
  ('High Knees', 'Full Body', 'bodyweight', 'conditioning', ARRAY['Rectus Femoris'], ARRAY['Gastrocnemius'], false, false),
  ('Bear Crawl', 'Full Body', 'bodyweight', 'conditioning', ARRAY['Deep Core'], ARRAY['Front Delt', 'Quads (Vastii)'], false, false),
  ('Jump Rope', 'Full Body', 'home', 'conditioning', ARRAY['Gastrocnemius'], ARRAY['Soleus'], false, false),
  ('Kettlebell Swing', 'Full Body', 'home', 'hinge', ARRAY['Glute Max', 'Hamstrings (Hip)'], ARRAY['Spinal Erectors', 'Deep Core'], true, false),
  ('Dumbbell Thruster', 'Full Body', 'home', 'conditioning', ARRAY['Quads (Vastii)', 'Front Delt'], ARRAY['Glute Max', 'Triceps Lateral Head'], true, false),
  ('Barbell Clean and Press', 'Full Body', 'full_gym', 'conditioning', ARRAY['Front Delt', 'Quads (Vastii)'], ARRAY['Upper Traps', 'Glute Max'], true, false),
  ('Barbell Clean', 'Full Body', 'full_gym', 'conditioning', ARRAY['Glute Max', 'Upper Traps'], ARRAY['Quads (Vastii)', 'Hamstrings (Hip)'], true, false),
  ('Barbell Snatch', 'Full Body', 'full_gym', 'conditioning', ARRAY['Glute Max', 'Upper Traps', 'Front Delt'], ARRAY['Quads (Vastii)'], true, false),
  ('Rowing Machine', 'Full Body', 'full_gym', 'conditioning', ARRAY['Lats', 'Quads (Vastii)'], ARRAY['Rhomboids', 'Biceps Long Head'], true, false),
  ('Battle Ropes', 'Full Body', 'full_gym', 'conditioning', ARRAY['Front Delt'], ARRAY['Deep Core', 'Side Delt'], false, false),
  ('Assault Bike', 'Full Body', 'full_gym', 'conditioning', ARRAY['Quads (Vastii)'], ARRAY['Front Delt', 'Lats'], false, false),
  ('Sled Push', 'Full Body', 'full_gym', 'conditioning', ARRAY['Quads (Vastii)', 'Glute Max'], ARRAY['Gastrocnemius'], true, false),
  ('Box Jump', 'Full Body', 'full_gym', 'conditioning', ARRAY['Quads (Vastii)', 'Glute Max'], ARRAY['Gastrocnemius'], true, false)
on conflict (name) where user_id is null do update set
  muscle_group      = excluded.muscle_group,
  equipment         = excluded.equipment,
  movement_pattern  = excluded.movement_pattern,
  primary_muscles   = excluded.primary_muscles,
  secondary_muscles = excluded.secondary_muscles,
  is_compound       = excluded.is_compound,
  is_unilateral     = excluded.is_unilateral;

-- Retire any exercise seeded by an older version of this file that is no
-- longer in the library, unless a user's template or log references it.
delete from public.exercises e
where e.user_id is null
  and e.name <> all (array[
    'Push-Up',
    'Dumbbell Bench Press',
    'Dumbbell Incline Press',
    'Dumbbell Fly',
    'Dumbbell Incline Fly',
    'Barbell Bench Press',
    'Incline Barbell Bench Press',
    'Decline Barbell Bench Press',
    'Chest Press Machine',
    'Incline Chest Press Machine',
    'Smith Machine Bench Press',
    'Cable Fly (Mid)',
    'Low-to-High Cable Fly',
    'High-to-Low Cable Crossover',
    'Pec Deck Machine',
    'Chest Dip',
    'Pull-Up',
    'Chin-Up',
    'Neutral-Grip Pull-Up',
    'Band-Assisted Pull-Up',
    'Lat Pulldown',
    'Neutral-Grip Lat Pulldown',
    'Assisted Pull-Up Machine',
    'Straight-Arm Pulldown',
    'Inverted Row',
    'Underhand Inverted Row',
    'Dumbbell Row',
    'Chest-Supported Dumbbell Row',
    'Resistance Band Pull-Apart',
    'Barbell Row',
    'T-Bar Row',
    'Seated Cable Row',
    'Single-Arm Cable Row',
    'Chest-Supported Machine Row',
    'Deadlift',
    'Trap Bar Deadlift',
    'Rack Pull',
    'Back Extension',
    '45-Degree Hyperextension',
    'Dumbbell Shrug',
    'Farmer''s Carry',
    'Barbell Shrug',
    'Pike Push-Up',
    'Elevated Pike Push-Up',
    'Dumbbell Shoulder Press',
    'Seated Dumbbell Press',
    'Barbell Overhead Press',
    'Push Press',
    'Shoulder Press Machine',
    'Landmine Press',
    'Lateral Raise',
    'Resistance Band Lateral Raise',
    'Cable Lateral Raise',
    'Machine Lateral Raise',
    'Bent-Over Reverse Fly',
    'Face Pull',
    'Reverse Pec Deck',
    'Cable Rear Delt Fly',
    'Front Raise',
    'External Rotation (Band)',
    'Dumbbell Bicep Curl',
    'Incline Dumbbell Curl',
    'Hammer Curl',
    'Resistance Band Curl',
    'Barbell Curl',
    'EZ-Bar Curl',
    'Preacher Curl',
    'Spider Curl',
    'Cable Curl',
    'Bayesian Cable Curl',
    'Tricep Dip (Bench)',
    'Diamond Push-Up',
    'Close-Grip Push-Up',
    'Bodyweight Skull Crusher',
    'Overhead Dumbbell Tricep Extension',
    'Single-Arm Overhead Extension',
    'Tricep Kickback',
    'Resistance Band Pushdown',
    'Close-Grip Bench Press',
    'Cable Tricep Pushdown',
    'Rope Pushdown',
    'Overhead Cable Extension',
    'Skull Crusher',
    'JM Press',
    'Tricep Dip Machine',
    'Dead Hang',
    'Wrist Curl (Dumbbell)',
    'Reverse Wrist Curl (Dumbbell)',
    'Plate Pinch Hold',
    'Barbell Reverse Curl',
    'Cable Wrist Curl',
    'Bodyweight Squat',
    'Jump Squat',
    'Wall Sit',
    'Goblet Squat',
    'Resistance Band Squat',
    'Barbell Back Squat',
    'Barbell Front Squat',
    'Hack Squat',
    'Leg Press',
    'Smith Machine Squat',
    'Pendulum Squat',
    'Leg Extension',
    'Sissy Squat',
    'Reverse Nordic Curl',
    'Lunge',
    'Walking Lunge',
    'Reverse Lunge',
    'Bulgarian Split Squat',
    'Step-Up',
    'Dumbbell Lunge',
    'Dumbbell Step-Up',
    'Single-Leg Deadlift (Bodyweight)',
    'Dumbbell Romanian Deadlift',
    'Dumbbell Stiff-Leg Deadlift',
    'Single-Leg Dumbbell RDL',
    'Barbell Romanian Deadlift',
    'Good Morning',
    'Nordic Curl',
    'Swiss Ball Leg Curl',
    'Lying Leg Curl',
    'Seated Leg Curl',
    'Glute Bridge',
    'Band Lateral Walk',
    'Dumbbell Hip Thrust',
    'Resistance Band Hip Thrust',
    'Barbell Hip Thrust',
    'Machine Hip Thrust',
    'Cable Glute Kickback',
    'Hip Abduction Machine',
    'Standing Calf Raise',
    'Single-Leg Calf Raise',
    'Dumbbell Calf Raise',
    'Seated Bodyweight Calf Raise',
    'Bent-Knee Wall Calf Raise',
    'Standing Calf Raise Machine',
    'Seated Calf Raise Machine',
    'Leg Press Calf Raise',
    'Plank',
    'Side Plank',
    'Dead Bug',
    'Hollow Body Hold',
    'Sit-Up',
    'Crunch',
    'Bicycle Crunch',
    'Leg Raise',
    'Flutter Kick',
    'V-Up',
    'Mountain Climber',
    'Russian Twist',
    'Weighted Russian Twist',
    'Weighted Sit-Up',
    'Ab Wheel Rollout',
    'Cable Crunch',
    'Hanging Leg Raise',
    'Captain''s Chair Leg Raise',
    'Landmine Twist',
    'Pallof Press',
    'Burpee',
    'Jumping Jack',
    'High Knees',
    'Bear Crawl',
    'Jump Rope',
    'Kettlebell Swing',
    'Dumbbell Thruster',
    'Barbell Clean and Press',
    'Barbell Clean',
    'Barbell Snatch',
    'Rowing Machine',
    'Battle Ropes',
    'Assault Bike',
    'Sled Push',
    'Box Jump'
  ])
  and not exists (select 1 from public.template_exercises t where t.exercise_id = e.id)
  and not exists (select 1 from public.logged_sets s where s.exercise_id = e.id);
